### ISSUE TITLE
Creating the hook version of this programmable chat

### ISSUE THREAD

**Issue by joemart** [philnash/react-programmable-chat#7]
Hello, I'm facing an issue where I initialize the Twilio object in ReactJS (using hooks) and then any method that I use is undefined.
```
 let chatClient = new TwilioChat(token.data.jwt)
            chatClient.createChannel({uniqueName:'General', friendlyName:'General Chat'})
```
         
I get` Channel with provided unique name already exists
`
and I get back `TypeError: Cannot read property 'getChannelByUniqueName' of undefined`
when using this method

**Comment by philnash** [comment]
Hey @joemart, thanks for raising an issue about this. This repo is a little out of date, with both React and Twilio Chat. However, I know what the issue is.

Due to the asynchronous nature of creating a chat client, we no longer recommend using the `new` constructor. Instead, you should use [`Twilio.Chat.Client.create`](http://media.twiliocdn.com/sdk/js/chat/releases/4.0.0/docs/Client.html#.create__anchor) which returns a Promise that resolves with a connected instance of a chat client. You could update your code to:

```js
(async () => {
  try {
    const chatClient = await TwilioChat.create(token.data.jwt);
    const channel = await createChannel(chatClient);
  } catch(error) {
    console.error("Chat client could not be created", error);
  }
})();
```

Watch out when you create a channel too, as that will throw if the channel already exists. Above I called out to a `createChannel` function, that could look something like this:

```js
const createChannel = async (client) => {
  let channel;
  try {
    channel = await client.createChannel({ uniqueName: "General", friendlyName: "General Chat" });
  } catch(error) {
    channel = await client.getChannelByUniqueName("General");
  }
  return channel;
}
```

Let me know if this helps at all.

**Comment by joemart** [comment]
You should wear a cape, because you are my hero. This solved the issue.

I just did a small snippet with this new information and sent a request with axios to the backend and just console logged the channel and it worked!

I can take it from here.

```
    const getToken2 = useCallback( async ()=>{
            const token = await axios.get(url)
            const chatClient = await TwilioChat.create(token.data.jwt)
            const channel = await chatClient.createChannel({uniqueName:"test4", friendlyName:"My test"})
            console.log(channel)

    },[url])
```

Thank you for the fast response!

**Comment by philnash** [comment]
Glad that it helped. Hope the rest of the app goes well 🙂
